---
name: Release Binaries

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  # adapted from https://github.com/starship/starship/blob/master/.github/workflows/deploy.yml

  build:
    name: Build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ref: https://github.com/rust-cross/rust-musl-cross#prebuilt-images
          - target: aarch64-unknown-linux-musl
            docker_tag: aarch64-musl
          - target: arm-unknown-linux-musleabi
            docker_tag: arm-musleabi
          - target: arm-unknown-linux-musleabihf
            docker_tag: arm-musleabihf
          - target: armv5te-unknown-linux-musleabi
            docker_tag: armv5te-musleabi
          - target: armv7-unknown-linux-musleabi
            docker_tag: armv7-musleabi
          - target: armv7-unknown-linux-musleabihf
            docker_tag: armv7-musleabihf
          - target: i686-unknown-linux-musl
            docker_tag: i686-musl
          - target: x86_64-unknown-linux-musl
            docker_tag: x86_64-musl

    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Prepare artifacts
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: scripts/build.sh
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}
          DOCKER_IMAGE_TAG: ${{ matrix.docker_tag }}

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv2parquet-${{ matrix.target }}
          path: dist/csv2parquet-${{ matrix.target }}
  publish:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          path: dict
          pattern: csv2parquet-*
      - name: Publish built binary to GitHub releases
        run: scripts/release.sh
        env:
          GH_TOKEN: ${{ github.token }}
